### ISSUE TITLE
Idea - Serialize/Deserialize Custom Types

### ISSUE THREAD

**Issue by gregLibert** [massalabs/as#277]
Currently, our transformer and tooling work with AS and TS native types.

I am proposing an extension to this functionality that would enable us to serialize/deserialize any type provided we have a specification for it.

## Proposal:

To accomplish this, we or the users (for specific/less common types) can provide a custom configuration file.
This file would instruct the toolkit/transformer on how to serialize/deserialize a particular type.

Here's an example of how such a configuration file might look:

```yml
- <type>
  - type:
    - proto: <underlying protobuf type>
    - import: <import string to import type>
  - serialize:
    - import: <import string to serialize function>
    - call: <serialize code> 
  - deserialize:
    - import: <import instruction to deserialize function>
    - call: <deserialize code>
```
The transformer and the toolkit could then utilize this configuration to generate helper functions.

### User code
Let's walk through an example using the U256 type and the add function:

```typescript
func add(a: U256, b: U256): U256 {
```

### Type configuration
A possible configuration file for AS might look like this:

```yml
- u256
  - type:
    - proto: bytes
    - import: "as-bignum/assembly"
  - serialize:
    - import: "as-bignum/assembly"
    - call: "\1.toStaticBytes();"
  - deserialize:
    - import: " as-bignum/assembly"
    - call: "u256.fromUint8ArrayLE(\1);"
```
### Code generation

With this configuration, the transformer could generate:

#### Protofile

```protofile
syntax = "proto3";
message sumHelper {
  bytes a = 1;
  bytes b = 2;
}
message sumRHelper {
  bytes value = 1;
}
```
#### AS code (receiving side)
```typescript
import {u256} from 'as-bignum/assembly';
import { decodeSumHelper } from "./sumHelper";
import { encodeSumRHelper } from "./sumRHelper";
...
export function sum(raw StaticArray<u8>): StaticArray<u8> {
  const pbDecoded = decodeSumhelper(raw)
  const result = _sum(u256.fromUint8ArrayLE(pbDecoded.a), u256.fromUint8ArrayLE(pbDecoded.b))
  return encodeSumRHelper(result.toStaticBytes())
}
```

#### AS code (calling side)
```typescript
import {u256} from 'as-bignum/assembly';
import { encodeSumHelper } from "./sumHelper";
import { decodeSumRHelper } from "./sumRHelper";
...
export function sum(a u256, b u256): u256 {
   let result = call(<address>, sum, encodeSumHelper(a.toStaticBytes(), b.toStaticBytes()), 0)
   return u256.fromUint8ArrayLE(decodeSumHelper(result))
}
```
