### ISSUE TITLE
Massa-type bignum serialization methods looks incorrect

### ISSUE THREAD

**Issue by bilboquet** [massalabs/as#293]
For those 2 functions:
```as
@massaExport()
export function test1(arg: u128) : u128 {
  return arg;
}

@massaExport()
export function test2(arg: u256) : u256 {
  return arg;
}
```
to build correctly

I needed to adjust [bignum.massa-type.yml](https://github.com/massalabs/as/blob/655f4e3a397b19cdacab2afe94b9711ac85e887a/packages/as-types/bignum.massa-type.yml)

this way:

```yaml
- type:
  name: u256
  proto: bytes
  import: "as-bignum/assembly"
  serialize: "\\1.toUint8Array()"    // <<<<<
  deserialize: "u256.fromUint8ArrayLE(\\1)"
- type:
  name: u128
  proto: bytes
  import: "as-bignum/assembly"
  serialize: "\\1.toUint8Array()"    // <<<<<
  deserialize: "u128.fromUint8ArrayLE(\\1)"
```

side note: the yaml file being modified, individually those two functions build correctly but when they are both in the same file the build fails. I'm looking at this.
